### ISSUE TITLE
Move all cancellation logic to EE

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/EveryElection#1972]
At the moment we can either cancel elections in EE or have YNR mark them as uncontested.

This gets complex quickly and means we have two sources of truth.

We also don't really present the reason for cancellation in EE, rather we have a boolean field and some other ways (metadata, seats contested) to work out what's going on.

The devs.DC API manages some of this logic for us:

https://github.com/DemocracyClub/aggregator-api/blob/master/api/endpoints/v1/voting_information/stitcher.py#L87-L105

We can move this 'up' into EE and simplify all downstream logic.

This looks like:

```[tasklist]
### Tasks
- [x] Move the CANCELLATION_REASONS dict in the above devs.DC link to EE
- [x] Add cancellation reason to Election model
- [x] Add the reasons as a drop down in the admin interface.
- [x] Migrate all previously cancelled elections to use cancellation reason (might be manual)
- [x] Expose CANCELLATION_REASON in the API
- [x] Update WDIV to consume this API and re-publish to devs.DC
- [x] Update devs.DC API to show cancellation reason from WDIV's API
- [ ] https://github.com/DemocracyClub/EveryElection/issues/1685
- [ ] https://github.com/DemocracyClub/EveryElection/issues/1939
- [ ] https://github.com/DemocracyClub/EveryElection/issues/1082
- [ ] https://github.com/DemocracyClub/EveryElection/issues/656
```

We're going to need to think about this a little more, but that's the basic outline.

Ideally we'd find a way for YNR to push new information to EE when we lock an uncontested ballot, but this might be too complex for the initial version. Better to improve the admin interface to allow users to to this manually, as this needs to be done anyway.

Once this is done, we can clean up the logic from the widget, WDIV, WCIVF and the Devs.DC API.

**Comment by Bekabyx** [comment]
Finished in DemocracyClub/EveryElection#2004
